# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
- azure_pipelines

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '19c5bad8-bedd-4c8f-8c72-ead439f9a190'

  # Web app name
  webAppName: 'online-job-portal'

  # Environment name
  environmentName: prasaya

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool: Pool

    steps:
    - script: |
        yarn
      displayName: 'Test Script'
      workingDirectory: $(System.DefaultWorkingDirectory)/src
