# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
- azure_pipelines

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '19c5bad8-bedd-4c8f-8c72-ead439f9a190'

  # Web app name
  webAppName: 'online-job-portal'

  # Environment name
  environmentName: prasaya

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build backend
    displayName: Build backend
    pool: Pool
    steps:
    - script: |
        yarn
      displayName: 'yarn install dependencies for backend'
      workingDirectory: $(System.DefaultWorkingDirectory)/src

  - job: Build frontend
    displayName: Build frontend
    pool: Pool
    steps:
    - script: |
        npm install
      displayName: 'npm install dependencies for frontend'
      workingDirectory: $(System.DefaultWorkingDirectory)/src/client

    - script: |
        npm run build
      displayName: 'npm build frontend'
      workingDirectory: $(System.DefaultWorkingDirectory)/src/client


- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool: Pool
    strategy:
      runOnce:
        deploy:
          steps:
          - script: yarn run start
          workingDirectory: $(System.DefaultWorkingDirectory)/src
