# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
- azure_pipelines

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '19c5bad8-bedd-4c8f-8c72-ead439f9a190'

  # Web app name
  webAppName: 'online-job-portal'

  # Environment name
  environmentName: prasaya

stages:
- stage: Build
  displayName: Build and Test stage
  pool:
    vmImage: 'ubuntu-latest'

  jobs:
  - job: Build
    displayName: Build job
    steps:
    - checkout: self
      clean: false

    - script: |
        yarn
      displayName: 'yarn install dependencies for backend'
      workingDirectory: $(System.DefaultWorkingDirectory)

    - script: |
        yarn
      displayName: 'yarn install dependencies for frontend'
      workingDirectory: $(System.DefaultWorkingDirectory)/src/client

    - script: yarn build
      displayName: 'yarn build for backend'
      workingDirectory: $(System.DefaultWorkingDirectory)

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          dist/**
          node_modules/**
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1

  # - job: Test
  #   displayName: Test code
  #   dependsOn: Build
  #   pool: Pool
  #   steps:
  #   - checkout: none

  #   - script: |
  #       yarn test
  #     displayName: 'yarn test for backend'
  #     workingDirectory: $(System.DefaultWorkingDirectory)

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy application
    environment:
      name: prasaya
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - script: |
              pm2 describe WebApp > /dev/null
              RUNNING=$?
              if [ "${RUNNING}" -ne 0 ]; then
                  pm2 start node --name WebApp -- dist/backend.cjs
              else
                pm2 reload WebApp
              fi;
            displayName: 'Run express application'
            workingDirectory: $(Build.ArtifactStagingDirectory)
